services:
  testDB:
    image: postgres
    container_name: testDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: TestBase
    volumes:
      - testDB:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d TestBase" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  testDB: