-- +goose Up
-- +goose StatementBegin
CREATE TABLE "people" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" varchar(256) NOT NULL,
                        "surname" varchar(256) NOT NULL,
                        "patronymic" varchar(256)
);

CREATE TABLE "info" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "person_id" int NOT NULL ,
                          "age" varchar(256) ,
                          "gender" varchar(256) ,
                          "nationality" varchar(256)
);

ALTER TABLE "info" ADD FOREIGN KEY ("person_id") REFERENCES "people" ("id");
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "info";
DROP TABLE IF EXISTS "people";
-- +goose StatementEnd
